apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: ruby-redis-app
  name: app-redis-config-map
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
  redis-service: my-release-redis-master:6379
