---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-redis-app
  creationTimestamp: null
  labels:
    app: ruby-redis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruby-redis-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ruby-redis-app
    spec:
      containers:
      - name: ruby-redis-app
        image: jasonchen/ruby_app:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort: 8080
        env:
          - name: REDIS_HOST
            value: redis-app
          - name: REDIS_PORT
            value: "6379"    
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ruby-redis-app-service
  labels:
    app: ruby-redis-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 9090
    targetPort: 8080
    nodePort: 3000
  selector:
    app: ruby-redis-app
