---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
  labels:
    app: ruby-redis-app
spec:
  selector:
    matchLabels:
      app: ruby-redis-app
  replicas: 1
  template:
    metadata:
      labels:
        app: ruby-redis-app
    spec:
      containers:
      - name: redis
        image: redis:5.0.4
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-app
  labels:
    app: ruby-redis-app
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: ruby-redis-app
